
redis:
  host: localhost
  port: 6379
  database: 0
  password:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fileresource
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver

#minio配置
minio:
  access-key: 3qUk0XPgTKLxx8Rf
  secret-key:  joUG6ShKxJNZtjqdzrnpO373czSfIiRr
  url: http://127.0.0.1:9008  #访问地址
  bucket-name: formal-file
  bucket-name-slice: slice-file

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    com.uniigym.resource: debug

